name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y libelf-dev
      - uses: actions/checkout@v2
        with:
          path: src
      - uses: actions/checkout@v2
        with:
          repository: torvalds/linux
          path: linux
      - run: make defconfig
        working-directory: linux
      - run: make -j$(nproc)
        working-directory: linux
      - run: make "KDIR=${{ github.workspace }}/linux"
        working-directory: src
